<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTMtAGHd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTMtAGHd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTMtAGHd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTMtAGHd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTMtAGHd\App_KernelDevDebugContainer([
    'container.build_hash' => 'TMtAGHd',
    'container.build_id' => 'f98af5c9',
    'container.build_time' => 1651439691,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTMtAGHd');
