#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_login:
  path: /api/login
  controller: App\Controller\SecurityController::login
  methods: [POST]

add_product:
  path: /api/products
  controller: App\Controller\ProductController::add_product
  methods: [POST]

edit_product:
  path: /api/products/{id}
  controller: App\Controller\ProductController::edit_product
  methods: [PUT]

delete_product:
  path: /api/products/{id}
  controller: App\Controller\ProductController::delete_product
  methods: [DELETE]

product_all:
  path: /api/products
  controller: App\Controller\ProductController::display_product
  methods: [GET]

product_id:
  path: /api/products/{id}
  controller: App\Controller\ProductController::getaproduct
  methods: [GET]

register_user:
  path: /api/register
  controller: App\Controller\SecurityController::register
  methods: [GET]
 

app_user_modify:
  path: /api/users/{id}
  controller: App\Controller\UserController::modify_user
  methods: [PUT]

order_id:
  path: /api/orders/{id}
  controller: App\Controller\OrderController::getaorder
  methods: [GET]

order_all:
  path: /api/orders
  controller: App\Controller\OrderController::display_orders
  methods: [GET]


  