<?php

namespace ContainerXkdpIZJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Command_DebugFirewallService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.command.debug_firewall' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Command/DebugFirewallCommand.php';

        $container->privates['security.command.debug_firewall'] = $instance = new \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand($container->parameters['security.firewalls'], ($container->privates['.service_locator.499SnRR'] ?? $container->get_ServiceLocator_499SnRRService()), ($container->privates['.service_locator.VzeOj7R'] ?? $container->load('get_ServiceLocator_VzeOj7RService')), ['login' => [0 => ($container->privates['security.authenticator.json_login.login'] ?? $container->load('getSecurity_Authenticator_JsonLogin_LoginService'))], 'users' => [0 => ($container->privates['security.authenticator.guard.users.0'] ?? $container->load('getSecurity_Authenticator_Guard_Users_0Service'))], 'products' => [0 => ($container->privates['security.authenticator.guard.products.0'] ?? $container->load('getSecurity_Authenticator_Guard_Products_0Service'))], 'products_id' => [0 => ($container->privates['security.authenticator.guard.products_id.0'] ?? $container->load('getSecurity_Authenticator_Guard_ProductsId_0Service'))], 'carts' => [0 => ($container->privates['security.authenticator.guard.carts.0'] ?? $container->load('getSecurity_Authenticator_Guard_Carts_0Service'))], 'carts_id' => [0 => ($container->privates['security.authenticator.guard.carts_id.0'] ?? $container->load('getSecurity_Authenticator_Guard_CartsId_0Service'))], 'orders' => [0 => ($container->privates['security.authenticator.guard.orders.0'] ?? $container->load('getSecurity_Authenticator_Guard_Orders_0Service'))], 'orders_id' => [0 => ($container->privates['security.authenticator.guard.orders_id.0'] ?? $container->load('getSecurity_Authenticator_Guard_OrdersId_0Service'))], 'main' => []], true);

        $instance->setName('debug:firewall');
        $instance->setDescription('Display information about your security firewall(s)');

        return $instance;
    }
}
